### ISSUE TITLE
[Jenkins] error on provisioning

### ISSUE THREAD

**Issue by lucasmellos** [storageos/use-cases#4]
I'm getting the following error on master when scaling a slave in jenkins:

<code>
2019-10-14 17:31:34.120+0000 [id=145]	WARNING	o.c.j.p.k.KubernetesLauncher#launch: Error in provisioning; agent=KubernetesSlave name: default-rn3nv, template=PodTemplate{inheritFrom='', name='default', namespace='', label='jenkins-agent', serviceAccount='default', nodeSelector='', nodeUsageMode=NORMAL, workspaceVolume=EmptyDirWorkspaceVolume [memory=false], containers=[ContainerTemplate{name='jnlp', image='jenkins/jnlp-slave:3.27-1', workingDir='/home/jenkins', command='', args='${computer.jnlpmac} ${computer.name}', resourceRequestCpu='200m', resourceRequestMemory='256Mi', resourceLimitCpu='200m', resourceLimitMemory='256Mi', envVars=[ContainerEnvVar [getValue()=jenkins:8080, getKey()=JENKINS_URL]], livenessProbe=org.csanchez.jenkins.plugins.kubernetes.ContainerLivenessProbe@117072e6}]}
java.lang.IllegalStateException: Agent is not connected after 5 seconds, status: Succeeded
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:190)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:297)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-14 17:31:34.121+0000 [id=145]	INFO	o.c.j.p.k.KubernetesSlave#_terminate: Terminating Kubernetes instance for agent default-rn3nv
Terminated Kubernetes instance for agent default/default-rn3nv
Disconnected computer default-rn3nv
2019-10-14 17:31:34.146+0000 [id=145]	INFO	o.c.j.p.k.KubernetesSlave#deleteSlavePod: Terminated Kubernetes instance for agent default/default-rn3nv
2019-10-14 17:31:34.146+0000 [id=145]	INFO	o.c.j.p.k.KubernetesSlave#_terminate: Disconnected computer default-rn3nv
2019-10-14 17:31:34.697+0000 [id=146]	INFO	o.j.p.workflow.job.WorkflowRun#finish: lis/dev #3 completed: ABORTED
</code>

PS: I'm trying to build a docker image

**Comment by Arau** [comment]
Hi @lucasmellos,

I can see in this message that the memory limit in the resources is different than the set in the example. Did you change that by any chance? If so, did you change the size of the JVM memory allocation?

**Comment by lucasmellos** [comment]
Hey @Arau!

Thanks for letting me know about this issue. This was part of my issue. I'm using Nginx Ingress and apparently my agents weren't connecting to the Jenkins svc due to my changes to port 80.

I ran in some problems related to OOM, thus I had to increase memory allocation in order to handle these problems in my agents.

May I publish a pull request supporting ingress?

**Comment by Arau** [comment]
Hi @lucasmellos ,

thank you for the information.

> Thanks for letting me know about this issue. This was part of my issue. I'm using Nginx Ingress and apparently my agents weren't connecting to the Jenkins svc due to my changes to port 80.

Feel free to PR against this repo and we will happily review.
 
> I ran in some problems related to OOM, thus I had to increase memory allocation in order to handle these problems in my agents.

You can either change the `XmX` config or the resources. I'm glad is working for you. 
For the sake of having a noted answer. Whenever a Pod starts with a JVM config that exceeds the request.limit of the Pod, the Kubernetes OOM killer will shoot that Pod at bootstrap because java allocates that memory when starts. I would set the `XmX` similar to the resource.request.
